// Declarative panel inventory for the public starter dashboard.
//
// Data only: no datasource UIDs, no cluster names, no saved selections. A
// `row` entry opens a section; every other entry is one panel, sized in
// Grafana's 24-column grid. Adding a panel is one line here.
//
// Consumed by runtime-triage.mjs, which turns these into Grafana panels with
// the foundation SDK.

export const PANELS = [

  // ── Triage Signals ──
  { row: "Triage Signals" },
  { type: "stat", title: "Scraped App Pods", unit: "none", w: 4, h: 4, queries: [{ expr: "sum(up{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"})", legend: "scraped pods" }] },
  { type: "stat", title: "Max Pod Memory / Limit", unit: "percentunit", w: 5, h: 4, queries: [{ expr: "max((max by (pod) (container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"${pod:regex}\", container=\"app\", image!=\"\"}) / max by (pod) (kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"${pod:regex}\", resource=\"memory\", exported_container=\"app\"})))", legend: "max pod usage / limit" }] },
  { type: "stat", title: "Restarts In 30m", unit: "short", w: 5, h: 4, queries: [{ expr: "sum(increase(kube_pod_container_status_restarts_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"${pod:regex}\", exported_container=\"app\"}[30m]))", legend: "restarts" }] },
  { type: "stat", title: "OOM Events In 30m", unit: "short", w: 5, h: 4, queries: [{ expr: "sum by () (max by (pod, name) (increase(container_oom_events_total{namespace=\"$namespace\", pod=~\"${pod:regex}\", container=\"app\"}[30m])))", legend: "oom events" }] },
  { type: "stat", title: "BEAM Binary Share", unit: "percentunit", w: 5, h: 4, queries: [{ expr: "max(vm_memory_binary_bytes{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"} / vm_memory_total_bytes{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"})", legend: "binary / total" }] },

  // ── Memory ──
  { row: "Memory" },
  { type: "timeseries", title: "Container Working Set vs Limit", unit: "bytes", w: 12, h: 8, queries: [{ expr: "max by (pod) (container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"${pod:regex}\", container=\"app\", image!=\"\"})", legend: "{{pod}} working set" }, { expr: "max by (pod) (kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"${pod:regex}\", resource=\"memory\", exported_container=\"app\"})", legend: "{{pod}} limit" }] },
  { type: "timeseries", title: "BEAM Memory Breakdown", unit: "bytes", w: 12, h: 8, queries: [{ expr: "vm_memory_total_bytes{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}", legend: "{{pod}} total" }, { expr: "vm_memory_processes_bytes{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}", legend: "{{pod}} processes" }, { expr: "vm_memory_binary_bytes{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}", legend: "{{pod}} binary" }, { expr: "vm_memory_ets_bytes{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}", legend: "{{pod}} ets" }, { expr: "vm_memory_code_bytes{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}", legend: "{{pod}} code" }, { expr: "vm_memory_atom_bytes{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}", legend: "{{pod}} atom" }, { expr: "vm_memory_atom_used_bytes{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}", legend: "{{pod}} atom used" }, { expr: "vm_memory_system_bytes{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}", legend: "{{pod}} system" }] },
  { type: "timeseries", title: "BEAM Process and Port Counts", unit: "short", w: 12, h: 7, queries: [{ expr: "vm_system_counts_process_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}", legend: "{{pod}} processes" }, { expr: "vm_system_counts_port_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}", legend: "{{pod}} ports" }] },
  { type: "timeseries", title: "BEAM Run Queue", description: "Total, CPU, and IO scheduler queues. Sudden growth usually means the VM is saturated or blocked on external work.", unit: "none", w: 12, h: 7, queries: [{ expr: "vm_total_run_queue_lengths_total{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}", legend: "{{pod}} total" }, { expr: "vm_total_run_queue_lengths_cpu{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}", legend: "{{pod}} cpu" }, { expr: "vm_total_run_queue_lengths_io{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}", legend: "{{pod}} io" }] },
  { type: "timeseries", title: "Cgroup Minus BEAM", description: "Container working set not accounted for by BEAM total memory. Use this to separate BEAM heap/binary growth from native allocator, libc, NIF, or cgroup accounting pressure.", unit: "bytes", w: 8, h: 7, queries: [{ expr: "clamp_min(max by (pod) (container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"${pod:regex}\", container=\"app\", image!=\"\"}) - on (pod) max by (pod) (vm_memory_total_bytes{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}), 0)", legend: "{{pod}} cgroup - beam" }] },
  { type: "timeseries", title: "Container RSS / Cache", description: "Cgroup memory categories from cAdvisor. RSS rising with flat BEAM memory points outside normal BEAM heap attribution.", unit: "bytes", w: 8, h: 7, queries: [{ expr: "max by (pod) (container_memory_rss{namespace=\"$namespace\", pod=~\"${pod:regex}\", container=\"app\", image!=\"\"})", legend: "{{pod}} rss" }, { expr: "max by (pod) (container_memory_cache{namespace=\"$namespace\", pod=~\"${pod:regex}\", container=\"app\", image!=\"\"})", legend: "{{pod}} cache" }, { expr: "max by (pod) (container_memory_mapped_file{namespace=\"$namespace\", pod=~\"${pod:regex}\", container=\"app\", image!=\"\"})", legend: "{{pod}} mapped file" }] },
  { type: "timeseries", title: "CPU Throttling Ratio", description: "CPU throttling can stretch request lifetimes and queues, increasing memory retained by in-flight requests.", unit: "percentunit", w: 8, h: 7, queries: [{ expr: "sum by (pod) (rate(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=~\"${pod:regex}\", container=\"app\", image!=\"\"}[$__rate_interval])) / clamp_min(sum by (pod) (rate(container_cpu_cfs_periods_total{namespace=\"$namespace\", pod=~\"${pod:regex}\", container=\"app\", image!=\"\"}[$__rate_interval])), 0.001)", legend: "{{pod}} throttled" }] },
  { type: "timeseries", title: "Workload Memory by Component", description: "App, worker, and scheduler cgroup memory in one view. App Prometheus metrics are scraped from the app service; worker/scheduler visibility here comes from Kubernetes cgroup metrics.", unit: "bytes", w: 12, h: 7, queries: [{ expr: "max by (pod, container) (container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"codex-pooler-(app|oban-worker|oban-scheduler).*\", container=~\"app|oban-worker|oban-scheduler\", image!=\"\"})", legend: "{{pod}} {{container}}" }] },
  { type: "timeseries", title: "CPU Usage", description: "App container CPU usage in cores. Correlate CPU spikes with request rate, DB query pressure, run queue, and admission queueing.", unit: "cores", w: 12, h: 7, queries: [{ expr: "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"${pod:regex}\", container=\"app\", image!=\"\"}[$__rate_interval]))", legend: "{{pod}} cpu" }] },

  // ── Gateway Pressure ──
  { row: "Gateway Pressure" },
  { type: "timeseries", title: "Request Rate", unit: "reqps", w: 8, h: 7, queries: [{ expr: "sum by (pod) (rate(phoenix_endpoint_stop_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval]))", legend: "{{pod}}" }] },
  { type: "timeseries", title: "Endpoint Duration p95", unit: "s", w: 8, h: 7, queries: [{ expr: "histogram_quantile(0.95, sum by (le, pod) (rate(phoenix_endpoint_stop_duration_seconds_bucket{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval])))", legend: "{{pod}} p95" }] },
  { type: "timeseries", title: "Slowest Routes p95", description: "Top active routes by p95 latency. The active-route filter avoids stale NaN/empty legend rows when a route has no observations in the current interval.", unit: "s", w: 8, h: 7, queries: [{ expr: "topk(8, histogram_quantile(0.95, sum by (le, route) (rate(phoenix_router_dispatch_stop_duration_seconds_bucket{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval]))) and on (route) (sum by (route) (rate(phoenix_router_dispatch_stop_duration_seconds_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval])) > 0))", legend: "{{route}} p95" }] },
  { type: "timeseries", title: "Stream Buffer Release Events", unit: "ops", w: 12, h: 7, queries: [{ expr: "sum by (buffer, transport, route_class, endpoint) (rate(codex_pooler_gateway_stream_buffer_oversized_count{namespace=\"$namespace\", pod=~\"${pod:regex}\"}[$__rate_interval]))", legend: "oversized {{transport}} {{route_class}} {{endpoint}}" }, { expr: "sum by (buffer, transport, route_class, endpoint) (rate(codex_pooler_gateway_stream_buffer_truncated_count{namespace=\"$namespace\", pod=~\"${pod:regex}\"}[$__rate_interval]))", legend: "truncated {{transport}} {{route_class}} {{endpoint}}" }] },
  { type: "timeseries", title: "Stream Buffer Size p95", description: "Oversized observations are saturated at 128 MiB for Prometheus histogram export, keeping p95 finite. This changes telemetry only, not stream-buffer handling or the raw telemetry event.", unit: "bytes", w: 12, h: 7, queries: [{ expr: "histogram_quantile(0.95, sum by (le, buffer, transport, route_class, endpoint) (rate(codex_pooler_gateway_stream_buffer_oversized_bytes_bucket{namespace=\"$namespace\", pod=~\"${pod:regex}\"}[$__rate_interval])))", legend: "oversized p95 {{transport}} {{route_class}} {{endpoint}}" }, { expr: "histogram_quantile(0.95, sum by (le, buffer, transport, route_class, endpoint) (rate(codex_pooler_gateway_stream_buffer_truncated_bytes_bucket{namespace=\"$namespace\", pod=~\"${pod:regex}\"}[$__rate_interval])))", legend: "truncated p95 {{transport}} {{route_class}} {{endpoint}}" }] },
  { type: "timeseries", title: "HTTP Route Rate", description: "Low-cardinality request rate by route, method, and status class. Use this to separate route-specific traffic growth from error storms.", unit: "reqps", w: 8, h: 7, queries: [{ expr: "sum by (route, method, status_class) (rate(codex_pooler_http_route_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval]))", legend: "{{route}} {{method}} {{status_class}}" }] },
  { type: "timeseries", title: "Admission Events", description: "Local gateway bulkhead pressure by route class and transport. Queue/reject/timeout spikes show admission backpressure before memory climbs.", unit: "ops", w: 8, h: 7, queries: [{ expr: "sum by (route_class, transport) (rate(codex_pooler_gateway_admission_accepted_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval]))", legend: "accepted {{route_class}} {{transport}}" }, { expr: "sum by (route_class, transport) (rate(codex_pooler_gateway_admission_enqueued_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval]))", legend: "enqueued {{route_class}} {{transport}}" }, { expr: "sum by (route_class, transport) (rate(codex_pooler_gateway_admission_dequeued_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval]))", legend: "dequeued {{route_class}} {{transport}}" }, { expr: "sum by (route_class, transport) (rate(codex_pooler_gateway_admission_rejected_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval]))", legend: "rejected {{route_class}} {{transport}}" }, { expr: "sum by (route_class, transport) (rate(codex_pooler_gateway_admission_timeout_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval]))", legend: "timeout {{route_class}} {{transport}}" }] },
  { type: "timeseries", title: "Admission Queue Time p95", description: "Time requests spent waiting in local admission queues before execution or timeout.", unit: "s", w: 8, h: 7, queries: [{ expr: "histogram_quantile(0.95, sum by (le, route_class, transport) (rate(codex_pooler_gateway_admission_dequeued_time_seconds_bucket{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval])))", legend: "dequeued {{route_class}} {{transport}} p95" }, { expr: "histogram_quantile(0.95, sum by (le, route_class, transport) (rate(codex_pooler_gateway_admission_timeout_time_seconds_bucket{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval])))", legend: "timeout {{route_class}} {{transport}} p95" }] },
  { type: "timeseries", title: "Admission Saturation", description: "Current per-pod local admission state. Sum only after selecting the pods you mean to inspect: each app pod reports its own running and queued work by route class.", unit: "short", w: 8, h: 7, queries: [{ expr: "codex_pooler_gateway_admission_running{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}", legend: "{{pod}} {{route_class}} running" }, { expr: "codex_pooler_gateway_admission_queued{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}", legend: "{{pod}} {{route_class}} queued" }] },

  // ── Database / Ecto Query Pressure ──
  { row: "Database / Ecto Query Pressure" },
  { type: "timeseries", title: "Repo Query Rate", unit: "ops", w: 8, h: 7, queries: [{ expr: "sum by (pod) (rate(codex_pooler_repo_query_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval]))", legend: "{{pod}}" }] },
  { type: "timeseries", title: "Queries / Request", unit: "short", w: 8, h: 7, queries: [{ expr: "sum by (pod) (rate(codex_pooler_repo_query_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval])) / clamp_min(sum by (pod) (rate(phoenix_endpoint_stop_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval])), 0.001)", legend: "{{pod}}" }] },
  { type: "timeseries", title: "Hot Query Sources", description: "Top Ecto query sources by safe source and SQL command. Source falls back to a sanitized table identifier for raw SQL when available.", unit: "ops", w: 8, h: 7, queries: [{ expr: "topk(10, sum by (source, command) (rate(codex_pooler_repo_query_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval])))", legend: "{{source}} {{command}}" }] },
  { type: "timeseries", title: "Repo Total Time p95", unit: "s", w: 8, h: 7, queries: [{ expr: "histogram_quantile(0.95, sum by (le, source, command) (rate(codex_pooler_repo_query_total_time_seconds_bucket{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval])))", legend: "{{source}} {{command}} p95" }] },
  { type: "timeseries", title: "DB Execution Time p95", unit: "s", w: 8, h: 7, queries: [{ expr: "histogram_quantile(0.95, sum by (le, source, command) (rate(codex_pooler_repo_query_query_time_seconds_bucket{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval])))", legend: "{{source}} {{command}} p95" }] },
  { type: "timeseries", title: "DB Queue Time p95", unit: "s", w: 8, h: 7, queries: [{ expr: "histogram_quantile(0.95, sum by (le, pod) (rate(codex_pooler_repo_query_queue_time_seconds_bucket{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval])))", legend: "{{pod}} p95" }] },
  { type: "timeseries", title: "Unknown Query Rate", description: "Source-less queries that could not be mapped to a safe Ecto source or table identifier. Use this to spot unclassified raw SQL or telemetry source-attribution gaps.", unit: "ops", w: 8, h: 7, queries: [{ expr: "sum by (pod, command) (rate(codex_pooler_repo_query_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\", source=\"unknown\"}[$__rate_interval]))", legend: "{{pod}} {{command}}" }] },
  { type: "timeseries", title: "Query Command Mix", description: "SQL command mix across repository queries. Useful for spotting unexpected write or transaction churn during incidents.", unit: "ops", w: 8, h: 7, queries: [{ expr: "sum by (command) (rate(codex_pooler_repo_query_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval]))", legend: "{{command}}" }] },
  { type: "timeseries", title: "Repo Queue Time by Source p95", description: "Database connection checkout pressure by safe source and command.", unit: "s", w: 8, h: 7, queries: [{ expr: "histogram_quantile(0.95, sum by (le, source, command) (rate(codex_pooler_repo_query_queue_time_seconds_bucket{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval])))", legend: "{{source}} {{command}} p95" }] },

  // ── Restart Evidence ──
  { row: "Restart Evidence" },
  { type: "timeseries", title: "Restarts and OOM Events", unit: "short", w: 12, h: 7, queries: [{ expr: "sum by (pod) (increase(kube_pod_container_status_restarts_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"${pod:regex}\", exported_container=\"app\"}[$__rate_interval]))", legend: "{{pod}} restarts" }, { expr: "sum by (pod) (max by (pod, name) (increase(container_oom_events_total{namespace=\"$namespace\", pod=~\"${pod:regex}\", container=\"app\"}[$__rate_interval])))", legend: "{{pod}} oom events" }] },
  { type: "table", title: "Current Pods Last Terminated Reason", description: "Current kube-state-metrics lastState.terminated reason for live pods only. Deleted pod history is covered by restart and OOM panels, not this table.", unit: "short", w: 12, h: 7, queries: [{ expr: "kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"${pod:regex}\", exported_container=\"app\"} == 1", legend: "{{pod}} {{reason}}" }] },

  // ── Admin Stats Dashboard ──
  { row: "Admin Stats Dashboard" },
  { type: "timeseries", title: "Admin Stats Reload Rate", description: "Admin stats LiveView reload scheduling, coalescing, cancellation, and execution rate by window and scope. Coalesced spikes mean a page is already waiting on one debounced reload.", unit: "ops", w: 8, h: 7, queries: [{ expr: "sum by (stage, window, scope) (rate(codex_pooler_admin_stats_reload_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval]))", legend: "{{stage}} {{window}} {{scope}}" }] },
  { type: "timeseries", title: "Admin Stats Dashboard Build Rate", description: "Full admin stats dashboard builds by outcome, selected time window, and scope. This shows the reload work that can drive read-model DB pressure from open admin pages.", unit: "ops", w: 8, h: 7, queries: [{ expr: "sum by (outcome, window, scope) (rate(codex_pooler_admin_stats_dashboard_build_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval]))", legend: "{{outcome}} {{window}} {{scope}}" }] },
  { type: "timeseries", title: "Admin Stats Dashboard Build p95", description: "p95 duration for full admin stats dashboard builds. Pair spikes here with hot query source and DB queue panels to identify expensive stats reload paths.", unit: "s", w: 8, h: 7, queries: [{ expr: "histogram_quantile(0.95, sum by (le, outcome, window, scope) (rate(codex_pooler_admin_stats_dashboard_build_duration_seconds_bucket{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval])))", legend: "{{outcome}} {{window}} {{scope}} p95" }] },
  { type: "timeseries", title: "Admin Request Logs Reload Rate", description: "Admin request-log LiveView reload rate by bounded stage and scope. Use this to separate first load, filter patch, and event-refresh pressure without tagging pool ids, models, request ids, users, paths, params, or API key prefixes.", unit: "ops", w: 12, h: 7, queries: [{ expr: "sum by (stage, scope) (rate(codex_pooler_admin_request_logs_reload_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval]))", legend: "{{stage}} {{scope}}" }] },
  { type: "timeseries", title: "Admin Request Logs Reload p95", description: "p95 admin request-log reload duration by bounded stage and scope. Pair spikes with DB queue, hot safe query source, and pg_stat_statements evidence when validating request-log read-path remediation.", unit: "s", w: 12, h: 7, queries: [{ expr: "histogram_quantile(0.95, sum by (le, stage, scope) (rate(codex_pooler_admin_request_logs_reload_duration_seconds_bucket{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval])))", legend: "{{stage}} {{scope}} p95" }] },

  // ── Gateway Outcomes ──
  { row: "Gateway Outcomes" },
  { type: "timeseries", title: "Stream Usage Completeness Rate", description: "Successful stream finalization rate. Compare usage_unknown against usage_known without request, account, model, or payload labels.", unit: "ops", w: 12, h: 9, queries: [{ expr: "sum by (usage_status, usage_source, downstream_transport, upstream_transport) (rate(codex_pooler_gateway_stream_finalization_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval]))", legend: "{{usage_status}} {{usage_source}} {{downstream_transport}} -> {{upstream_transport}}" }] },
  { type: "timeseries", title: "Stream Outcome Rate", description: "First-settlement stream outcomes by bounded outcome and downstream or upstream transport. The metric has at most 45 series per app pod.", unit: "ops", w: 12, h: 9, queries: [{ expr: "sum by (outcome, downstream_transport, upstream_transport) (rate(codex_pooler_gateway_stream_outcome_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval]))", legend: "{{outcome}} {{downstream_transport}} -> {{upstream_transport}}" }] },
  { type: "timeseries", title: "Websocket Bridge Fallback Rate", description: "Pre-content bridge fallbacks by bounded reason. There are at most 20 reason series per app pod; precommit buffer overflows remain a separate untagged counter.", unit: "ops", w: 12, h: 9, queries: [{ expr: "sum by (reason) (rate(codex_pooler_gateway_websocket_bridge_fallback_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval]))", legend: "{{reason}}" }, { expr: "sum(rate(codex_pooler_gateway_websocket_bridge_precommit_overflow_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval]))", legend: "precommit overflow" }] },
  { type: "timeseries", title: "Quota Cycle Decision Rate", description: "Quota cycle refresh, confirmation, candidate, rejection, and superseded-primary rejection rate. Repeated candidate decisions indicate a convergence loop.", unit: "ops", w: 12, h: 9, queries: [{ expr: "sum by (scope, decision, source) (rate(codex_pooler_quota_cycle_decision_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval]))", legend: "{{scope}} {{decision}} {{source}}" }] },
  { type: "timeseries", title: "Routing Circuit Transitions", description: "Routing circuit transition rate by bounded transition, route class, and reason class. Compare open, half-open, and closed transitions.", unit: "ops", w: 12, h: 9, queries: [{ expr: "sum by (transition, route_class, reason_class) (rate(codex_pooler_gateway_routing_circuit_transition_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval]))", legend: "{{transition}} {{route_class}} {{reason_class}}" }] },
  { type: "timeseries", title: "Ingress Firewall Denial Rate", description: "Ingress firewall denials by bounded scope and reason. These denials happen before authenticated request accounting.", unit: "ops", w: 12, h: 9, queries: [{ expr: "sum by (scope, reason) (rate(codex_pooler_ingress_firewall_denied_count{namespace=\"$namespace\", job=\"codex-pooler-app\", pod=~\"${pod:regex}\"}[$__rate_interval]))", legend: "{{scope}} {{reason}}" }] },
];
