defmodule CodexPooler.Dev.Seeds.RealTraffic do
  @moduledoc false

  import Ecto.Query

  alias CodexPooler.Access
  alias CodexPooler.Access.APIKey
  alias CodexPooler.Accounts.{Scope, User}
  alias CodexPooler.Pools.Pool
  alias CodexPooler.Repo

  @seed_key "codex_pooler_real_traffic_seed"
  @pool_slug "dev-real-traffic"
  @pool_name "Dev Real Traffic Pool"
  @bootstrap_dir Path.join(["tmp", "dev-seed"])
  @env_path Path.join(@bootstrap_dir, "real-traffic.env")

  @spec pool_slug() :: String.t()
  def pool_slug, do: @pool_slug

  @spec env_path() :: String.t()
  def env_path, do: @env_path

  # Reruns keep the Pool and whatever was imported into it, revoke the keys an
  # earlier run minted and mint one new key, so exactly one seed key is active.
  @spec run(%{required(:owner) => User.t()}) :: map()
  def run(%{owner: owner}) do
    scope = Scope.for_user(owner, ["instance_owner"])
    pool = ensure_pool!(owner)
    revoked = revoke_seed_keys!(scope, pool)

    {:ok, %{api_key: api_key, raw_key: raw_key}} =
      Access.create_api_key(scope, pool, %{
        display_name: "Dev real traffic key",
        metadata: %{labels: ["dev", "real-traffic"], dev_seed: @seed_key, operator_notes: "Generated by local dev seeds"}
      })

    write_env!(pool, raw_key)
    %{pool: pool, api_key: api_key, revoked_api_keys: revoked, env_path: @env_path}
  end

  defp ensure_pool!(owner) do
    case Repo.get_by(Pool, slug: @pool_slug) do
      %Pool{status: "active"} = pool ->
        pool

      %Pool{} ->
        raise "Pool #{@pool_slug} exists but is not active; reactivate or remove it first"

      nil ->
        timestamp = DateTime.utc_now() |> DateTime.truncate(:microsecond)

        %Pool{}
        |> Pool.changeset(%{
          slug: @pool_slug,
          name: @pool_name,
          status: "active",
          created_by_user_id: owner.id,
          created_at: timestamp,
          updated_at: timestamp
        })
        |> Repo.insert!()
    end
  end

  defp revoke_seed_keys!(scope, %Pool{id: pool_id}) do
    from(key in APIKey,
      where: key.pool_id == ^pool_id and key.status == "active" and fragment("?->>?", key.metadata, "dev_seed") == @seed_key
    )
    |> Repo.all()
    |> Enum.map(fn key ->
      {:ok, _revoked} = Access.revoke_api_key(scope, key)
      key.id
    end)
    |> length()
  end

  defp write_env!(pool, raw_key) do
    File.mkdir_p!(@bootstrap_dir)
    File.chmod!(@bootstrap_dir, 0o700)
    File.rm(@env_path)
    File.touch!(@env_path)
    File.chmod!(@env_path, 0o600)
    File.write!(@env_path, "CODEX_POOLER_REAL_TRAFFIC_API_KEY=#{raw_key}\nCODEX_POOLER_REAL_TRAFFIC_POOL_SLUG=#{pool.slug}\n")
  end
end
