apiVersion: v2
name: codex-pooler
description: Helm chart for the Codex Pooler Phoenix release and operational jobs
type: application
version: 0.1.24
# x-release-please-start-version
appVersion: 0.0.1
# x-release-please-end
